name: ModLoader
version: 2.0.0
main: com.example.modloader.ModLoader
api-version: '1.21'
author: Erik99948
description: A universal content engine for PaperMC.

commands:
  modloader:
    description: ModLoader999 management commands.
    usage: /<command> [list|reload|enable|disable|load|unload|hotreload|gui|marketplace|help]
    permission: modloader.admin
    permission-message: You do not have permission to use this command.

permissions:
  modloader.admin:
    description: Allows full access to ModLoader999 commands.
    default: op
  modloader.reload:
    description: Allows reloading of ModLoader999 mods.
    default: op
  modloader.enable:
    description: Allows enabling of ModLoader999 mods.
    default: op
  modloader.disable:
    description: Allows disabling of ModLoader999 mods.
    default: op
  modloader.marketplace:
    description: Allows access to the ModLoader999 marketplace.
    default: true
